export const store = {
  name: "Tee House",
  currency: "USD",
  categories: ["Basics", "Graphic", "Oversized", "Premium", "Athletic"],
  products: [
    {
      id: "t001",
      name: "Classic Crew Neck Tee",
      category: "Basics",
      price: 19.99,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      colors: ["White", "Black", "Navy", "Grey"],
      description: "100% combed cotton crew neck tee, pre-shrunk, 180 gsm. Everyday essential.",
      inStock: true,
    },
    {
      id: "t002",
      name: "Vintage Band Tee",
      category: "Graphic",
      price: 34.99,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Washed Black", "Charcoal"],
      description: "Retro-washed graphic tee with distressed print. Relaxed fit, soft hand feel.",
      inStock: true,
    },
    {
      id: "t003",
      name: "Heavyweight Boxy Tee",
      category: "Oversized",
      price: 44.99,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Cream", "Black", "Olive", "Slate"],
      description: "300 gsm heavyweight cotton, dropped shoulders, boxy silhouette. Streetwear staple.",
      inStock: true,
    },
    {
      id: "t004",
      name: "Pima Cotton V-Neck",
      category: "Premium",
      price: 49.99,
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["White", "Black", "Heather Grey", "Dusty Rose"],
      description: "Luxuriously soft Pima cotton V-neck, 200 gsm, slim fit. Elevated basics.",
      inStock: true,
    },
    {
      id: "t005",
      name: "Dri-Fit Performance Tee",
      category: "Athletic",
      price: 29.99,
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["Black", "Royal Blue", "Neon Green"],
      description: "Moisture-wicking polyester blend, raglan sleeves, reflective logo. Gym to street.",
      inStock: true,
    },
    {
      id: "t006",
      name: "Striped Pocket Tee",
      category: "Basics",
      price: 24.99,
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Navy/White Stripe", "Green/White Stripe", "Red/White Stripe"],
      description: "Breton-style striped tee with chest pocket. 100% cotton jersey.",
      inStock: true,
    },
    {
      id: "t007",
      name: "Abstract Art Print Tee",
      category: "Graphic",
      price: 39.99,
      sizes: ["S", "M", "L", "XL"],
      colors: ["White", "Sand"],
      description: "Original abstract artwork screen-printed on front. Limited run, 220 gsm organic cotton.",
      inStock: false,
    },
    {
      id: "t008",
      name: "Linen Blend Tee",
      category: "Premium",
      price: 54.99,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Natural", "Sky Blue", "Sage"],
      description: "55% linen, 45% cotton blend tee. Breathable, textured, perfect for warm weather.",
      inStock: true,
    },
    {
      id: "t009",
      name: "Acid Wash Oversized Tee",
      category: "Oversized",
      price: 37.99,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Washed Purple", "Washed Blue", "Washed Grey"],
      description: "Unique acid wash finish, oversized drop-shoulder fit. Each piece is one-of-a-kind.",
      inStock: true,
    },
    {
      id: "t010",
      name: "Compression Base Layer",
      category: "Athletic",
      price: 34.99,
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["Black", "White", "Dark Grey"],
      description: "Second-skin compression fit, flatlock seams, UV 50+ protection. Training essential.",
      inStock: true,
    },
  ],
};
